version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db.petstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Logitech17

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/probelyLearn
    ports:

      - "127.0.0.1:8000:8000"
    depends_on:
      - db


