# Generated by Django 3.2.5 on 2021-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210702_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photoUrls',
            field=models.URLField(blank=True),
        ),
    ]
